version: '3.7'

services:
  mongodb:
    container_name: file-manager-db
    
    image: mongo:latest
    
    ports:
      - 27017:27017
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=pwd

    
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

